#!/usr/bin/env bash
# This script uses a while loop to:
# display "bad luck" on the 4th iteration
# display "good luck" on the 8th iteration
# display "Best School" on other iterations

count=0

while [ $count -lt 10 ]
do
	if [ $count -eq 3 ]
	then
		echo "bad luck"
	elif [ $count -eq 7 ]
	then
		echo "good luck"
	else
		echo "Best School"
	fi
	(( count++ ))
done

