#!/usr/bin/env bash
# this script displays:
# numbers from 1 to 20 but,
# it displays " bad luck from China" for the 4th iteration,
# it displays " bad luck from Japan" for the 9th iteration,
# it displays " bad luck from Italy" fot the 17th iteration

count=1

while [ $count -le 20 ]
do
	echo "$count"
	case $count in
		"4") echo "bad luck from China";;
		"9") echo "bad luck from Japan";;
		"17") echo "bad luck from Italy";;
	esac
	(( count++ ))
done

