#!/usr/bin/env bash
# this script displays time for 12 hours and 59 minutes
# it displays hours from 0 to 12
# and also displays minutes from 1 to 59

hour=0

while [ $hour -le 12 ]
do
	echo "Hour: $hour"
	minute=1
	while [ $minute -le 59 ]
	do
		echo "$minute"
		(( minute++ ))
	done
	(( hour++ ))
done

