#!/usr/bin/env bash
# this script displays the contents of our current directory
# and it only displays the part of the name after the first dash

list=$(ls)
for i in $list; do
	echo "$i" | cut -d '-' -f2
done

